-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: Agora/schema/tables.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/agora_comments (
  comment_id INT UNSIGNED AUTO_INCREMENT NOT NULL,
  page_id INT UNSIGNED NOT NULL,
  comment_actor_id BIGINT UNSIGNED NOT NULL,
  comment_parent_id INT UNSIGNED DEFAULT NULL,
  comment_posted_time BINARY(14) NOT NULL,
  comment_latest_rev_id INT UNSIGNED DEFAULT NULL,
  comment_deleted_actor INT UNSIGNED DEFAULT NULL,
  INDEX comment_page (page_id),
  INDEX comment_page_posted_time (page_id, comment_posted_time),
  INDEX comment_parent (comment_parent_id),
  INDEX comment_actor_posted_time (
    comment_actor_id, comment_posted_time
  ),
  INDEX comment_latest_rev (comment_latest_rev_id),
  PRIMARY KEY(comment_id)
) /*$wgDBTableOptions*/;


CREATE TABLE /*_*/agora_comment_revision (
  comment_rev_id INT UNSIGNED AUTO_INCREMENT NOT NULL,
  comment_id INT UNSIGNED NOT NULL,
  comment_rev_actor_id BIGINT UNSIGNED NOT NULL,
  comment_rev_timestamp BINARY(14) NOT NULL,
  comment_html MEDIUMBLOB NOT NULL,
  comment_wikitext MEDIUMBLOB NOT NULL,
  INDEX comment_rev_comment (comment_id),
  INDEX comment_rev_comment_time (
    comment_id, comment_rev_timestamp
  ),
  INDEX comment_rev_actor_time (
    comment_rev_actor_id, comment_rev_timestamp
  ),
  PRIMARY KEY(comment_rev_id)
) /*$wgDBTableOptions*/;
